# coding: utf-8

# flake8: noqa

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "CarsApi",
    "RentalsApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "CarCreate",
    "CarResponse",
    "HTTPValidationError",
    "RentalCreate",
    "RentalResponse",
    "ValidationError",
    "ValidationErrorLocInner",
]

# import apis into sdk package
from openapi_client.api.cars_api import CarsApi as CarsApi
from openapi_client.api.rentals_api import RentalsApi as RentalsApi

# import ApiClient
from openapi_client.api_response import ApiResponse as ApiResponse
from openapi_client.api_client import ApiClient as ApiClient
from openapi_client.configuration import Configuration as Configuration
from openapi_client.exceptions import OpenApiException as OpenApiException
from openapi_client.exceptions import ApiTypeError as ApiTypeError
from openapi_client.exceptions import ApiValueError as ApiValueError
from openapi_client.exceptions import ApiKeyError as ApiKeyError
from openapi_client.exceptions import ApiAttributeError as ApiAttributeError
from openapi_client.exceptions import ApiException as ApiException

# import models into sdk package
from openapi_client.models.car_create import CarCreate as CarCreate
from openapi_client.models.car_response import CarResponse as CarResponse
from openapi_client.models.http_validation_error import HTTPValidationError as HTTPValidationError
from openapi_client.models.rental_create import RentalCreate as RentalCreate
from openapi_client.models.rental_response import RentalResponse as RentalResponse
from openapi_client.models.validation_error import ValidationError as ValidationError
from openapi_client.models.validation_error_loc_inner import ValidationErrorLocInner as ValidationErrorLocInner

