# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.car_response import CarResponse

class TestCarResponse(unittest.TestCase):
    """CarResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CarResponse:
        """Test CarResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CarResponse`
        """
        model = CarResponse()
        if include_optional:
            return CarResponse(
                id = 56,
                make = '',
                model = '',
                year = 56,
                daily_rate = 1.337,
                available = True
            )
        else:
            return CarResponse(
                id = 56,
                make = '',
                model = '',
                year = 56,
                daily_rate = 1.337,
                available = True,
        )
        """

    def testCarResponse(self):
        """Test CarResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
