# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.rentals_api import RentalsApi


class TestRentalsApi(unittest.TestCase):
    """RentalsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RentalsApi()

    def tearDown(self) -> None:
        pass

    def test_active_rentals_rentals_active_get(self) -> None:
        """Test case for active_rentals_rentals_active_get

        Active Rentals
        """
        pass

    def test_cancel_rental_rentals_rental_id_delete(self) -> None:
        """Test case for cancel_rental_rentals_rental_id_delete

        Cancel Rental
        """
        pass

    def test_list_rentals_rentals_get(self) -> None:
        """Test case for list_rentals_rentals_get

        List Rentals
        """
        pass

    def test_rent_car_rentals_car_id_rent_post(self) -> None:
        """Test case for rent_car_rentals_car_id_rent_post

        Rent Car
        """
        pass


if __name__ == '__main__':
    unittest.main()
