# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.cars_api import CarsApi


class TestCarsApi(unittest.TestCase):
    """CarsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CarsApi()

    def tearDown(self) -> None:
        pass

    def test_create_car_cars_post(self) -> None:
        """Test case for create_car_cars_post

        Create Car
        """
        pass

    def test_get_car_cars_car_id_get(self) -> None:
        """Test case for get_car_cars_car_id_get

        Get Car
        """
        pass

    def test_list_cars_cars_get(self) -> None:
        """Test case for list_cars_cars_get

        List Cars
        """
        pass


if __name__ == '__main__':
    unittest.main()
